Task 18: добавить cd
YaWokrshopJavaTeam/yandex-workshop-task-service pull request #1
Opened 2024-12-07 11:13 UTC by Hyacintholuscus

2024-12-08 10:50 UTC, druzhininyury requested changes
Я добавил комментарии, там в последних версиях всякого разного чуть по-другому стало.

Отдельно, теперь в docker-compose.yml файле строка version устаревшая. Её рекомендуют убрать.

2024-12-08 10:50 UTC, druzhininyury commented on .github/workflows/cd.yml
> +          source: ya-workshop-task-service.tar
Можно объединить два копирования в одно. В последней версии это делает так:
source: "file1,file2,file3"

2024-12-08 10:50 UTC, druzhininyury commented on .github/workflows/cd.yml
> +            docker-compose down
В последней версии докера убрали программу docker-compose, а её функции возложили на docker engine. Это означает, что теперь всё работает так:
docker compose down

2024-12-10 06:13 UTC, KurakinPavel approved these changes

2024-12-10 06:38 UTC, druzhininyury approved these changes

2024-12-10 11:13 UTC, merged